### PR TITLE
fixed TypeError: 'str' does not support the buffer interfacein python 3

### PR DESCRIPTION
**Pull request by theboocock**
Fixed an error when using the buffer interface in python3. Hope this works and helps.

### CODE REVIEW

**Comment by brentp** [comment]
thanks!

**Comment by mruffalo** [comment]
I'm really curious about this now -- there are only three places in the actual pyfasta code where files are opened in binary mode: twice for writing (`wb`) and once for reading (`rb`). These file handles need objects that support the buffer protocol in order to deal with raw bytes instead of Unicode characters, but they're only used for `pickle.load` and `pickle.dump`.

The only other place that I can find a `bytes`/`str` mismatch is in `ez_setup.py`; I didn't really spend much time on that file. [This line](https://github.com/brentp/pyfasta/blob/master/ez_setup.py#L261) reads a `bytes` object from `srcfile`, and [this line](https://github.com/brentp/pyfasta/blob/master/ez_setup.py#L263) checks it against a text-mode regex. This will fail; sorry for missing this before.

Even then, this `TypeError` doesn't mention anything about the buffer protocol (same exception message on both 3.2 and 3.3):

```
Python 3.3.1 (default, Apr 17 2013, 22:30:32) 
[GCC 4.7.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> match = re.search("\nmd5_data = {\n([^}]+)}", b'some bytes')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.3/re.py", line 161, in search
    return _compile(pattern, flags).search(string)
TypeError: can't use a string pattern on a bytes-like object
```

@smilefreak, can you paste the full traceback here?

**Comment by theboocock** [comment]
2to3-3.3 -w pyfasta/*

running install
Checking .pth file support in /usr/local/lib/python3.3/dist-packages/
/usr/bin/python3 -E -c pass
TEST PASSED: /usr/local/lib/python3.3/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
creating pyfasta.egg-info
writing dependency_links to pyfasta.egg-info/dependency_links.txt
writing entry points to pyfasta.egg-info/entry_points.txt
writing top-level names to pyfasta.egg-info/top_level.txt
writing pyfasta.egg-info/PKG-INFO
writing manifest file 'pyfasta.egg-info/SOURCES.txt'
reading manifest file 'pyfasta.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pyfasta.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/pyfasta
copying pyfasta/**init**.py -> build/lib/pyfasta
copying pyfasta/records.py -> build/lib/pyfasta
copying pyfasta/split_fasta.py -> build/lib/pyfasta
copying pyfasta/fasta.py -> build/lib/pyfasta
Skipping implicit fixer: buffer
Skipping implicit fixer: idioms
Skipping implicit fixer: set_literal
Skipping implicit fixer: ws_comma
Can't parse build/lib/pyfasta/split_fasta.py: ParseError: bad input: type=22, value='=', context=('', (51, 37))
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pyfasta
copying build/lib/pyfasta/**init**.py -> build/bdist.linux-x86_64/egg/pyfasta
copying build/lib/pyfasta/records.py -> build/bdist.linux-x86_64/egg/pyfasta
copying build/lib/pyfasta/split_fasta.py -> build/bdist.linux-x86_64/egg/pyfasta
copying build/lib/pyfasta/fasta.py -> build/bdist.linux-x86_64/egg/pyfasta
byte-compiling build/bdist.linux-x86_64/egg/pyfasta/**init**.py to **init**.cpython-33.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyfasta/records.py to records.cpython-33.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyfasta/split_fasta.py to split_fasta.cpython-33.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyfasta/fasta.py to fasta.cpython-33.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pyfasta.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyfasta.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyfasta.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyfasta.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyfasta.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyfasta.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/pyfasta-0.4.5-py3.3.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pyfasta-0.4.5-py3.3.egg
creating /usr/local/lib/python3.3/dist-packages/pyfasta-0.4.5-py3.3.egg
Extracting pyfasta-0.4.5-py3.3.egg to /usr/local/lib/python3.3/dist-packages
Adding pyfasta 0.4.5 to easy-install.pth file
Installing pyfasta script to /usr/local/bin

Installed /usr/local/lib/python3.3/dist-packages/pyfasta-0.4.5-py3.3.egg
Processing dependencies for pyfasta==0.4.5
Finished processing dependencies for pyfasta==0.4.5

Python 3.3.1 (default, Apr 17 2013, 22:30:32) 
[GCC 4.7.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
i>>> from pyfasta import Fasta

> > > a = Fasta('/home/smilefreak/pyfasta/tests/data
> > > \  File "<stdin>", line 1
> > >     a = Fasta('/home/smilefreak/pyfasta/tests/data
> > >                                                  ^
> > > SyntaxError: EOL while scanning string literal
> > > a = Fasta('/home/smilefreak/pyfasta/tests/data/key.fasta')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "./pyfasta/fasta.py", line 57, in **init**
> > >     flatten_inplace)
> > >   File "./pyfasta/records.py", line 64, in prepare
> > >     flatfh.write(bytes(seq,'UTF-8'))
> > > TypeError: must be str, not bytes

So it doesnt work on 3.3.1 but I use 3.3.2 on my server. Ill post the traceback of that now.

**Comment by theboocock** [comment]
Ok so my bad disregard my change you guys already changed from buffer 'wb' to 'w' sorry for wasting you time. 

My bad sorry.

**Comment by mruffalo** [comment]
Ah, that makes sense. Opening text files in text mode is one of the first changes I made (f441b5eda736969af25121f7ae38cf845a80a38f) and v0.4.5 on PyPI predates my Python 3 compatibility changes.

@smilefreak You don't need to run 2to3 yourself before `setup.py`. The code is converted automatically during a `setup.py build`, and 2to3 runs are usually not idempotent. Your first 2to3 run drops the `__future__.print_function` imports, and the second (automated) run can't parse the code since it isn't valid Python 2 anymore. The

```
Can't parse build/lib/pyfasta/split_fasta.py: ParseError: bad input: type=22, value='=', context=('', (51, 37))
```

line is 2to3 failing to parse the new `print(something, file=sys.stderr)` syntax, since this isn't valid Python 2 and there's no `__future__` import.

Also, the usual way to get a `bytes` from a `str` is `str.encode(encoding)` :)

**Pull request merged**
