### PR TITLE
Add option to use zero based coords in sequence

### PR DESCRIPTION
**Pull request by jamescasbon**

### CODE REVIEW

**Comment by brentp** [comment]
can you add a test and not use the "ternary" as I think python2.4 is still otherwise fully supporting.
something like: 

```
start = f['start'] - int(one_based)
```

should work.

**Comment by jamescasbon** [comment]
Test + no ternary in my master.

**Comment by brentp** [comment]
Thanks. Did you push it to github? I can't see it.

**Comment by jamescasbon** [comment]
Oops, no.  Just did.  Actually, I realised it needed to go into _seq_from_keys as well - have committed that.

**Pull request merged**
